// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/futureproof/DenseManifesto.tsx": () => import("../components/mockups/futureproof/DenseManifesto.tsx"),
  "./components/mockups/futureproof/LandingPage.tsx": () => import("../components/mockups/futureproof/LandingPage.tsx"),
  "./components/mockups/futureproof/WarmEditorial.tsx": () => import("../components/mockups/futureproof/WarmEditorial.tsx")
};
